name: TPMDriver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.0
  auto_size_text: ^2.1.0
  badges: ^1.1.3
  bottom_navy_bar: ^5.5.0
  cached_network_image: ^2.3.3
  carousel_slider: ^2.3.1
  charts_flutter: ^0.9.0
  circle_button: ^1.0.1
  clipboard: ^0.1.2+8
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  encrypt: ^4.0.0
  fancy_on_boarding: ^1.7.0
  flutter_audio_recorder: ^0.5.5
  flutter_countdown_timer: ^4.0.2
  flutter_html: ^1.1.1
  flutter_plugin_android_lifecycle: ^1.0.11
  flutter_svg: ^0.19.3
  flutter_verification_code: ^0.2.1
  font_awesome_flutter: ^8.10.0
  get_storage: ^1.3.2
  google_fonts: ^1.1.1
  http: ^0.12.2
  http_parser: ^3.1.4
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  ionicons: ^0.0.3
  line_icons: ^0.2.0
  loading: ^1.0.2
  md2_tab_indicator: ^1.0.2
  mime: ^0.9.7
  modal_bottom_sheet: ^1.0.0+1
  path: ^1.7.0
  path_provider: ^1.6.24
  percent_indicator: ^2.1.8
  pie_chart: ^4.0.1
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  rxdart: ^0.24.1
  select_dialog: ^1.2.1
  shared_preferences: ^0.5.12+2
  skeleton_text: ^1.0.0
  toast: ^0.1.5
  tuple: ^1.0.3
  video_player: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/menu/
    # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
